version: '3.7'

networks:
  boiler:
    name: boiler
    external: true

services:
  php:
    container_name: boiler-php
    image: ${HUB}/php:${TAG}
    build:
      context: .
      target: app_php
    env_file: .env
    volumes:
      - /opt/docker/boiler/php_socket:/var/run/php
      - php_socket:/var/run/php
    networks:
      - boiler
    restart: unless-stopped

  nginx:
    container_name: boiler-nginx
    image: ${HUB}/nginx:${TAG}
    build:
      context: .
      target: nginx
    depends_on:
      - php
    volumes:
      - ./public:/application/public:delegated
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:delegated
      - php_socket:/var/run/php
    ports:
      - "9500:80"
    networks:
      - boiler
    restart: unless-stopped
    
volumes:
  php_socket:
