version: "3.7"

# Development environment override
services:
    php:
        env_file: .env.local
        build:
            target: app_php_dev
        volumes:
            - ./:/application
            - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
        environment:
            XDEBUG_MODE: "${XDEBUG_MODE:-debug}"
            PHP_IDE_CONFIG: "serverName=Docker"
        extra_hosts:
            - host.docker.internal:host-gateway
