version: '3.7'

networks:
  boiler:
    name: boiler

services:
  mysql:
    image: mysql:8.0
    container_name: boiler-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boiler
      MYSQL_USER: boiler
      MYSQL_PASSWORD: boiler
    volumes:
      - /opt/docker/boiler/mysql:/var/lib/mysql
    networks:
      - boiler
    ports:
      - "9502:3306"
    restart: unless-stopped
